### ISSUE TITLE
AttributeError: 'Dwarf' object has no attribute 'write_jmap_wcs'

### ISSUE THREAD

**Issue by NAH8** [fermiPy/dmsky#2]
I was testing the wcs_template_example.ipynb and I got this error when I ran the fourth part:

"image,pix,wcs = draco.create_jmap(npix=150,subsample=8,coordsys='CEL',projection='AIT')"

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-46-563bcb44e84a> in <module>()
      2 
      3 # Create a template image and associate wcs
----> 4 image,pix,wcs = draco.create_jmap(npix=150,subsample=8,coordsys='CEL',projection='AIT')
      5 # The image is in the default units [cgs]
      6 #image = Units.convert_to(image,'GeV2 / cm5')

/u/gl/nah/.local/lib/python2.7/site-packages/pymodeler/model.pyc in __getattr__(self, name)
    148         else:
    149             # Raises AttributeError
--> 150             return object.__getattribute__(self,name)
    151 
    152     def __setattr__(self, name, value):

AttributeError: 'Dwarf' object has no attribute 'create_jmap'

**Comment by NAH8** [comment]
I started with trying to run dmpipe-prepare-targets and I think the errors are related:
$ dmpipe-prepare-targets --roster dsphs_gc --baseconfig config.yaml --topdir TOPDIR5
/afs/slac.stanford.edu/u/gl/nah/.local/lib/python2.7/site-packages/dmsky/data/targets
/afs/slac.stanford.edu/u/gl/nah/.local/lib/python2.7/site-packages/dmsky/data/rosters
Writing bootes_I:default
Traceback (most recent call last):
  File "/u/gl/nah/.local/bin/dmpipe-prepare-targets", line 11, in <module>
    load_entry_point('dmpipe==0.0.1+12.g041aca0.dirty', 'console_scripts', 'dmpipe-prepare-targets')()
  File "build/bdist.linux-x86_64/egg/dmpipe/target_analysis.py", line 413, in main_prepare_targets
  File "build/bdist.linux-x86_64/egg/dmpipe/target_analysis.py", line 120, in run_analysis
  File "build/bdist.linux-x86_64/egg/dmpipe/target_analysis.py", line 99, in write_target_dirs
  File "/afs/slac.stanford.edu/u/gl/nah/.local/lib/python2.7/site-packages/pymodeler/model.py", line 150, in __getattr__
    return object.__getattribute__(self,name)
AttributeError: 'Dwarf' object has no attribute 'write_jmap_wcs'
